### ISSUE TITLE
New library?

### ISSUE THREAD

**Issue by guidone** [dialogs/js-bot-sdk#1]
Hi guys,

does this library replace the @dlghq/dialog-bot-sdk ?

What is this endpoints option:

```
endpoints: ['https://grpc-test.transmit.im:9443']
```
is it pointing to a chatserver or is a callback from your servers? It's not clear in the example.

Thanks

**Comment by german-st** [comment]
Hello.
Join the issue

**Comment by Drymonade** [comment]
Hi everyone! 

> does this library replace the @dlghq/dialog-bot-sdk ?

Yes, js-bot-sdk is the new library for grpc-based version of the Dialog (which will be available soon), while @dlghq/dialog-bot-sdk is deprecated now. 

> is it pointing to a chatserver or is a callback from your servers? It's not clear in the example.

Endpoint is a chat server address.
