### ISSUE TITLE
Is 4.0.0 a breaking protocol update?

### ISSUE THREAD

**Issue by terorie** [dialogs/js-bot-sdk#2]
I'm getting `Error: 13 INTERNAL: Failed to parse server response` when connecting to https://grpc-test.transmit.im:9443 in the newer versions.

Version 3.4.3 works, 3.5.0 and 4.0.0 are broken for me.
I guess this is because the server is not updated to the new model yet?

Also, could you please unpublish 3.5.0 from npm?
It's a breaking update (`onMessages` refactored) but it gets installed with selector `^3.4.3`, breaking existing apps. 4.0.0 is fine because it doesn't match `^3.4.3`.

**Comment by nkt** [comment]
@terorie yep, it's been a breaking change, we'll update grpc-test soon.
